name: Setup TailwindCSS
description: Install TailwindCSS standalone binary for CSS compilation

inputs:
  version:
    description: TailwindCSS version to install
    required: false
    default: 'v3.4.15'
  github-token:
    description: GitHub token for authenticated downloads (increases rate limit)
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Cache TailwindCSS binary
      id: cache-tailwind
      uses: actions/cache@v4
      with:
        path: /tmp/tailwind-bin/tailwindcss
        key: tailwindcss-standalone-${{ runner.os }}-x64-${{ inputs.version }}

    - name: Install TailwindCSS
      if: steps.cache-tailwind.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail
        echo "::group::Installing TailwindCSS ${{ inputs.version }}"

        # Create directory for tailwind binary
        mkdir -p /tmp/tailwind-bin

        # Download TailwindCSS standalone binary with authentication
        DOWNLOAD_URL="https://github.com/tailwindlabs/tailwindcss/releases/download/${{ inputs.version }}/tailwindcss-linux-x64"
        echo "Downloading from: $DOWNLOAD_URL"

        if ! curl -sSfL \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -o /tmp/tailwind-bin/tailwindcss \
          "$DOWNLOAD_URL"; then
          echo "::error::Failed to download TailwindCSS binary from $DOWNLOAD_URL"
          exit 1
        fi

        echo "TailwindCSS ${{ inputs.version }} downloaded successfully"
        echo "::endgroup::"

    - name: Make binary executable and add to PATH
      shell: bash
      run: |
        # Make binary executable (whether cached or freshly downloaded)
        chmod +x /tmp/tailwind-bin/tailwindcss

        # Add to PATH
        echo "/tmp/tailwind-bin" >> $GITHUB_PATH
