version: "2"

run:
  timeout: 10000s
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-files:
    - pkg/graphql/graphql.go
  exclude-dirs:
    - pkg/fp
    - postgres-data
    - py-embed
    - docs
    - logs
    - e2e
    - migrations
  exclude-rules:
    # Allow nil comparison for controllers that may return nil in production builds
    - path: "modules/core/module\\.go"
      text: "SA4023"
      linters:
        - staticcheck
output:
  format: colored-line-number
  sort-results: true
  sort-order:
    - linter
    - severity
    - file

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA4023"  # Allow "always true" comparisons for build-tagged nil checks


linters:
  enable:
    - asasalint
  disable:
    - errcheck      # many test setup/teardown; enable incrementally
    - exhaustive    # many switches; add default cases incrementally
    - forbidigo     # println in debug/example code
    - unused        # mocks and reserved code in tests
    - predeclared   # id/err variable naming
    - prealloc      # slice preallocation style
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    #    - containedctx
    #    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    #    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - forbidigo
    #    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoinits  # Disabled: we use init() for build-tagged conditional feature registration
    - gochecksumtype
    #    - gocognit
    #    - goconst
    #    - gocyclo
    #    - godot
    #    - gofmt
    #    - gofumpt
    - goheader
    #    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    #    - gosimple
    #    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    #    - intrange
    #    - lll
    - loggercheck
    #    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    #    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    #    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    #    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    #    - stylecheck
    - testableexamples
    # - testifylint  # disabled: style-only, many test updates needed
    # - thelper      # disabled: test helper convention
    - unconvert
    #    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

