run:
  timeout: 10000s
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-files:
    - pkg/graphql/graphql.go
  exclude-dirs:
    - pkg/fp
    - postgres-data
    - py-embed
    - docs
    - logs
    - e2e
    - migrations

output:
  formats:
    - format: colored-line-number
      path: stderr

  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  # print lines of code with issue, default is true
  print-issued-lines: false
  # print linter name in the end of issue text, default is true
  print-linter-name: true


linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    #    - containedctx
    #    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    #    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - forbidigo
    #    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    #    - gocognit
    #    - goconst
    #    - gocyclo
    #    - godot
    - gofmt
    #    - gofumpt
    - goheader
    #    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    #    - intrange
    #    - lll
    - loggercheck
    #    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    #    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    #    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    #    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    #    - stylecheck
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    #    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

