services:
  db:
    image: postgres:15.1
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "logging_collector=off", "-c", "max_connections=500" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iota_erp
    ports:
      - "5432:5432"
    volumes:
      - sdk-data:/var/lib/postgresql/data

volumes:
  sdk-data:

