services:
  erp_local:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      GO_APP_ENV: testing
      DB_NAME: iota_erp
      DB_HOST: erp_db
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DOMAIN: iota.uz
      SESSION_DURATION: 720h
      MEILI_URL: http://meilisearch:7700
    depends_on:
      - erp_db
      - meilisearch

  erp_db:
    image: postgres:15.1
    restart: always
    hostname: erp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iota_erp

  redis:
    image: redis:latest
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: always
    hostname: meilisearch
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
