FROM golang:1.23.2-alpine

WORKDIR /app

# Install required system dependencies
RUN apk add --no-cache \
    gcc \
    musl-dev \
    git \
    nodejs \
    npm \
    curl \
    make

# Install Air for hot reloading
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.5

# Install TailwindCSS
RUN npm install -g tailwindcss@3.4.13

# Install templ
RUN go install github.com/a-h/templ/cmd/templ@v0.2.793

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download Go modules
RUN go get ./...

# Copy the rest of the application
COPY . .

# Set Air to run on container startup
ENTRYPOINT ["air"]

