version: '3.8'

services:
  erp:
    restart: always
    build:
      context: .
      target: staging
    environment:
      GO_APP_ENV: production
      DB_NAME: iota_erp
      DB_HOST: erp_db
      DB_PORT: 5432
      DB_PASSWORD: 2dP9L9d6gB9597
      DOMAIN: erp.ci.iota.uz
      SESSION_DURATION: 720h
      GOOGLE_CLIENT_ID: 1234567890.apps.googleusercontent.com # TODO: Change this
      GOOGLE_CLIENT_SECRET: 123456789
      GOOGLE_REDIRECT_URL: https://erp.ci.iota.uz/auth/google/callback
      OPENAI_KEY: sk-1234567890 # TODO: Change this
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp.rule=Host(`erp.ci.iota.uz`)"
      - "traefik.http.routers.erp.tls=true"
      - "traefik.http.routers.erp.tls.certresolver=letsencrypt"
      - "traefik.http.services.erp.loadbalancer.server.port=3200"
    depends_on:
      - erp_db
    networks:
      - app

  erp_db:
    image: postgres:15.1
    restart: always
    hostname: erp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2dP9L9d6gB9597
      POSTGRES_DB: iota_erp
    volumes:
      - ~/volumes/erp/postgres/data:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    name: app
    external: true
