package role

import "github.com/iota-agency/iota-erp/internal/domain/entities/permission"

var (
	CEO = Role{
		ID:          1,
		Name:        "CEO",
		Description: "Chief Executive Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	Owner = Role{
		ID:          2,
		Name:        "Owner",
		Description: "Owner",
		Permissions: []permission.Permission{
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	CCO = Role{
		ID:          3,
		Name:        "CCO",
		Description: "Chief Commercial Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	CFO = Role{
		ID:          4,
		Name:        "CFO",
		Description: "Chief Financial Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	CPO = Role{
		ID:          5,
		Name:        "CPO",
		Description: "Chief Product Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	CMO = Role{
		ID:          6,
		Name:        "CMO",
		Description: "Chief Marketing Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	COO = Role{
		ID:          7,
		Name:        "COO",
		Description: "Chief Operating Officer",
		Permissions: []permission.Permission{
			permission.PaymentCreate,
			permission.PaymentRead,
			permission.PaymentUpdate,
			permission.PaymentDelete,
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	CTO = Role{
		ID:          8,
		Name:        "CTO",
		Description: "Chief Technology Officer",
		Permissions: []permission.Permission{
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
	ProjectManager = Role{
		ID:          9,
		Name:        "Project Manager",
		Description: "Project Manager",
		Permissions: []permission.Permission{
			permission.UserCreate,
			permission.UserRead,
			permission.UserUpdate,
			permission.UserDelete,
			permission.RoleCreate,
			permission.RoleRead,
			permission.RoleUpdate,
			permission.RoleDelete,
			permission.AccountCreate,
			permission.AccountRead,
			permission.AccountUpdate,
			permission.AccountDelete,
			permission.ProjectCreate,
			permission.ProjectRead,
			permission.ProjectUpdate,
			permission.ProjectDelete,
			permission.StageCreate,
			permission.StageRead,
			permission.StageUpdate,
			permission.StageDelete,
		},
	}
)
