// Phosphor geometry is MIT licensed. See PHOSPHOR-LICENSE.
import { splitProps, type JSX, type Component } from 'solid-js';
import geometry from './geometry.json';
export interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string | number;
    weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
    mirrored?: boolean;
    className?: string;
}
function Icon(props: IconProps & {
    name: keyof typeof geometry;
}) {
    const [local, native] = splitProps(props, ['name', 'size', 'weight', 'mirrored', 'className', 'class']);
    return <svg {...native} width={local.size ?? '1em'} height={local.size ?? '1em'} viewBox="0 0 256 256" fill={props.color ?? 'currentColor'} class={local.class ?? local.className} aria-hidden={props['aria-label'] ? undefined : true} style={local.mirrored ? { "transform": 'scaleX(-1)' } : undefined} innerHTML={geometry[local.name][local.weight ?? 'regular']}/>;
}
export const Archive = (props: IconProps) => <Icon {...props} name="Archive"/>;
export const ArrowClockwise = (props: IconProps) => <Icon {...props} name="ArrowClockwise"/>;
export const ArrowCounterClockwise = (props: IconProps) => <Icon {...props} name="ArrowCounterClockwise"/>;
export const ArrowDown = (props: IconProps) => <Icon {...props} name="ArrowDown"/>;
export const ArrowLeft = (props: IconProps) => <Icon {...props} name="ArrowLeft"/>;
export const ArrowRight = (props: IconProps) => <Icon {...props} name="ArrowRight"/>;
export const ArrowSquareOut = (props: IconProps) => <Icon {...props} name="ArrowSquareOut"/>;
export const ArrowUUpLeft = (props: IconProps) => <Icon {...props} name="ArrowUUpLeft"/>;
export const ArrowUp = (props: IconProps) => <Icon {...props} name="ArrowUp"/>;
export const ArrowsClockwise = (props: IconProps) => <Icon {...props} name="ArrowsClockwise"/>;
export const ArrowsCounterClockwise = (props: IconProps) => <Icon {...props} name="ArrowsCounterClockwise"/>;
export const ArrowsIn = (props: IconProps) => <Icon {...props} name="ArrowsIn"/>;
export const ArrowsOut = (props: IconProps) => <Icon {...props} name="ArrowsOut"/>;
export const Bookmark = (props: IconProps) => <Icon {...props} name="Bookmark"/>;
export const Brain = (props: IconProps) => <Icon {...props} name="Brain"/>;
export const Bug = (props: IconProps) => <Icon {...props} name="Bug"/>;
export const CaretDown = (props: IconProps) => <Icon {...props} name="CaretDown"/>;
export const CaretLeft = (props: IconProps) => <Icon {...props} name="CaretLeft"/>;
export const CaretLineLeft = (props: IconProps) => <Icon {...props} name="CaretLineLeft"/>;
export const CaretLineRight = (props: IconProps) => <Icon {...props} name="CaretLineRight"/>;
export const CaretRight = (props: IconProps) => <Icon {...props} name="CaretRight"/>;
export const CaretUp = (props: IconProps) => <Icon {...props} name="CaretUp"/>;
export const CaretUpDown = (props: IconProps) => <Icon {...props} name="CaretUpDown"/>;
export const ChartBar = (props: IconProps) => <Icon {...props} name="ChartBar"/>;
export const ChatCircle = (props: IconProps) => <Icon {...props} name="ChatCircle"/>;
export const ChatCircleDots = (props: IconProps) => <Icon {...props} name="ChatCircleDots"/>;
export const Check = (props: IconProps) => <Icon {...props} name="Check"/>;
export const CheckCircle = (props: IconProps) => <Icon {...props} name="CheckCircle"/>;
export const Circle = (props: IconProps) => <Icon {...props} name="Circle"/>;
export const CircleNotch = (props: IconProps) => <Icon {...props} name="CircleNotch"/>;
export const Clock = (props: IconProps) => <Icon {...props} name="Clock"/>;
export const ClockCounterClockwise = (props: IconProps) => <Icon {...props} name="ClockCounterClockwise"/>;
export const Code = (props: IconProps) => <Icon {...props} name="Code"/>;
export const Columns = (props: IconProps) => <Icon {...props} name="Columns"/>;
export const Copy = (props: IconProps) => <Icon {...props} name="Copy"/>;
export const Crown = (props: IconProps) => <Icon {...props} name="Crown"/>;
export const Database = (props: IconProps) => <Icon {...props} name="Database"/>;
export const DotsThree = (props: IconProps) => <Icon {...props} name="DotsThree"/>;
export const DotsThreeVertical = (props: IconProps) => <Icon {...props} name="DotsThreeVertical"/>;
export const Download = (props: IconProps) => <Icon {...props} name="Download"/>;
export const DownloadSimple = (props: IconProps) => <Icon {...props} name="DownloadSimple"/>;
export const File = (props: IconProps) => <Icon {...props} name="File"/>;
export const FileCode = (props: IconProps) => <Icon {...props} name="FileCode"/>;
export const FileCsv = (props: IconProps) => <Icon {...props} name="FileCsv"/>;
export const FileDoc = (props: IconProps) => <Icon {...props} name="FileDoc"/>;
export const FileMagnifyingGlass = (props: IconProps) => <Icon {...props} name="FileMagnifyingGlass"/>;
export const FilePdf = (props: IconProps) => <Icon {...props} name="FilePdf"/>;
export const FileText = (props: IconProps) => <Icon {...props} name="FileText"/>;
export const FileXls = (props: IconProps) => <Icon {...props} name="FileXls"/>;
export const FloppyDisk = (props: IconProps) => <Icon {...props} name="FloppyDisk"/>;
export const Gear = (props: IconProps) => <Icon {...props} name="Gear"/>;
export const Image = (props: IconProps) => <Icon {...props} name="Image"/>;
export const ImageBroken = (props: IconProps) => <Icon {...props} name="ImageBroken"/>;
export const Info = (props: IconProps) => <Icon {...props} name="Info"/>;
export const Lightbulb = (props: IconProps) => <Icon {...props} name="Lightbulb"/>;
export const Lightning = (props: IconProps) => <Icon {...props} name="Lightning"/>;
export const List = (props: IconProps) => <Icon {...props} name="List"/>;
export const Lock = (props: IconProps) => <Icon {...props} name="Lock"/>;
export const MagnifyingGlass = (props: IconProps) => <Icon {...props} name="MagnifyingGlass"/>;
export const MagnifyingGlassMinus = (props: IconProps) => <Icon {...props} name="MagnifyingGlassMinus"/>;
export const MagnifyingGlassPlus = (props: IconProps) => <Icon {...props} name="MagnifyingGlassPlus"/>;
export const Package = (props: IconProps) => <Icon {...props} name="Package"/>;
export const PaperPlaneRight = (props: IconProps) => <Icon {...props} name="PaperPlaneRight"/>;
export const PaperPlaneTilt = (props: IconProps) => <Icon {...props} name="PaperPlaneTilt"/>;
export const Paperclip = (props: IconProps) => <Icon {...props} name="Paperclip"/>;
export const PencilSimple = (props: IconProps) => <Icon {...props} name="PencilSimple"/>;
export const PencilSimpleLine = (props: IconProps) => <Icon {...props} name="PencilSimpleLine"/>;
export const Plus = (props: IconProps) => <Icon {...props} name="Plus"/>;
export const ShareNetwork = (props: IconProps) => <Icon {...props} name="ShareNetwork"/>;
export const Sidebar = (props: IconProps) => <Icon {...props} name="Sidebar"/>;
export const Spinner = (props: IconProps) => <Icon {...props} name="Spinner"/>;
export const SpinnerGap = (props: IconProps) => <Icon {...props} name="SpinnerGap"/>;
export const Stack = (props: IconProps) => <Icon {...props} name="Stack"/>;
export const Stop = (props: IconProps) => <Icon {...props} name="Stop"/>;
export const Table = (props: IconProps) => <Icon {...props} name="Table"/>;
export const Timer = (props: IconProps) => <Icon {...props} name="Timer"/>;
export const Trash = (props: IconProps) => <Icon {...props} name="Trash"/>;
export const UserPlus = (props: IconProps) => <Icon {...props} name="UserPlus"/>;
export const Users = (props: IconProps) => <Icon {...props} name="Users"/>;
export const UsersThree = (props: IconProps) => <Icon {...props} name="UsersThree"/>;
export const Warning = (props: IconProps) => <Icon {...props} name="Warning"/>;
export const WarningCircle = (props: IconProps) => <Icon {...props} name="WarningCircle"/>;
export const Wrench = (props: IconProps) => <Icon {...props} name="Wrench"/>;
export const X = (props: IconProps) => <Icon {...props} name="X"/>;
export const XCircle = (props: IconProps) => <Icon {...props} name="XCircle"/>;
export type IconComponent = Component<IconProps>;
