name: Setup Backend Environment
description: Set up Go environment with dependencies and tools for backend development

inputs:
  go-version:
    description: Go version to install
    required: false
    default: '1.24.10'
  install-templ:
    description: Whether to install templ tool
    required: false
    default: 'true'
  install-golangci-lint:
    description: Whether to install golangci-lint
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: useblacksmith/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Download Go dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Downloading Go modules"
        if ! go mod download; then
          echo "::error::Failed to download Go modules. Check go.mod for errors."
          exit 1
        fi
        echo "::endgroup::"

    - name: Install templ tool
      if: inputs.install-templ == 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Installing templ"
        if ! go install github.com/a-h/templ/cmd/templ@v0.3.857; then
          echo "::error::Failed to install templ tool"
          exit 1
        fi
        echo "Installed templ version:"
        templ version || echo "templ installed successfully"
        echo "::endgroup::"

    - name: Install golangci-lint
      if: inputs.install-golangci-lint == 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Installing golangci-lint"
        # Use go install instead of curl script to avoid GitHub API rate limits/503 errors
        if ! go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.2; then
          echo "::error::Failed to install golangci-lint"
          exit 1
        fi
        echo "Installed golangci-lint version:"
        golangci-lint version
        echo "::endgroup::"
