name: Claude — Issue Implementation Plan

on:
  issues:
    types: [opened]

jobs:
  implementation-plan:
    name: Generate Plan
    uses: iota-uz/.github/.github/workflows/cc-shared-issue-plan.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      BLOOM_MCP_TOKEN: ${{ secrets.BLOOM_MCP_TOKEN }}
    with:
      base_branch: staging
      tech_stack: iota-sdk
      project_id: PVT_kwDOCGNubc4AvE2N
      project_owner: iota-uz
      prompt: |
        **Additional Context:**
        This application follows Domain-Driven Design (DDD) architecture with strict layer separation.
        Pay special attention to DDD principles and ensure proper separation between domain, infrastructure, services, and presentation layers.