name: Update Code Index
on:
  push:
    branches:
      - staging
jobs:
  index:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache code indexer merkle data
        uses: useblacksmith/cache@v5
        with:
          path: ~/.codeindexer
          key: ${{ runner.os }}-codeindexer-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-codeindexer-staging
            ${{ runner.os }}-codeindexer-
      
      - uses: useblacksmith/setup-node@v5
        with: { node-version: '20' }
      
      - run: |
          npm install @code-indexer/core
          node .github/scripts/index-codebase.js
    env:
      MILVUS_ADDRESS: ${{ secrets.MILVUS_ADDRESS }}
      MILVUS_TOKEN:   ${{ secrets.MILVUS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}