name: Update Code Index
on: [push]
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: |
          npx -y @code-indexer/mcp@latest \
              --repo . \
              --milvus $MILVUS_ADDRESS \
              --milvus-token $MILVUS_TOKEN \
              --openai-key $OPENAI_API_KEY \
              --sync \
              --once          # exits after indexing
    env:
      MILVUS_ADDRESS: ${{ secrets.MILVUS_ADDRESS }}
      MILVUS_TOKEN:   ${{ secrets.MILVUS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}